# Toolchain description for macOS on x86_64.
#
# Paths are relative to this file's directory.

[toolchain]
id = "macos-x86_64"
target = "macos"
arch = "x86_64"
triple = "x86_64-apple-macosx"

[build]
cxx_std = "c++17"
c_flags = ["-isysroot", "MacOSX.sdk"]
objc_flags = []
include = []

[link]
driver = "ld64.lld"
lib_paths = []
libs = ["objc", "c", "z", "resolv", "c++", "System", "dl"]
frameworks = ["Security", "WebKit", "Foundation"]
objects = ["openssl_libs/libssl.a", "openssl_libs/libcrypto.a"]
flags = [
  "-w",
  "-dynamic",
  "-arch", "x86_64",
  "-demangle",
  "-platform_version", "macos", "11.0.0", "11.0.0",
  "-syslibroot", "MacOSX.sdk",
]
