//! The `peko.lock` lockfile.
//!
//! The lockfile pins each resolved dependency to an exact version and, for
//! registry packages, the `.pkpkg` checksum that download verifies against. It
//! is generated by resolution and read on later builds to reproduce the same
//! dependency set.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use super::ConfigError;

/// The file name of a lockfile.
pub const LOCKFILE_FILE: &str = "peko.lock";

/// The lockfile format version this module reads and writes.
pub const LOCKFILE_VERSION: u32 = 1;

/// A parsed `peko.lock`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Lockfile {
    /// The lockfile format version.
    pub version: u32,
    /// One entry per resolved package, sorted by name then version.
    #[serde(default, rename = "package")]
    pub packages: Vec<LockedPackage>,
}

/// One resolved package pinned in the lockfile.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockedPackage {
    /// The package name.
    pub name: String,
    /// The exact resolved version.
    pub version: String,
    /// The `.pkpkg` checksum, present for registry packages.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
    /// Where the package was resolved from.
    pub source: LockSource,
    /// For a path source, the dependency directory relative to the project
    /// root.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<PathBuf>,
}

/// Where a locked package was resolved from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum LockSource {
    /// Resolved through the registry.
    Registry,
    /// Resolved from a local path.
    Path,
}

impl Lockfile {
    /// Build a lockfile from resolved packages, sorted for stable output.
    pub fn new(mut packages: Vec<LockedPackage>) -> Lockfile {
        packages.sort_by(|left, right| {
            left.name
                .cmp(&right.name)
                .then_with(|| left.version.cmp(&right.version))
        });
        Lockfile {
            version: LOCKFILE_VERSION,
            packages,
        }
    }

    /// The lockfile path for a project root.
    pub fn path_in(root: &Path) -> PathBuf {
        root.join(LOCKFILE_FILE)
    }

    /// Read and parse the lockfile at the given path.
    pub fn load<P: AsRef<Path>>(path: P) -> Result<Lockfile, ConfigError> {
        let path = path.as_ref();
        let text = std::fs::read_to_string(path).map_err(|source| ConfigError::Io {
            path: path.to_path_buf(),
            source,
        })?;
        toml::from_str(&text).map_err(|source| ConfigError::Parse {
            path: path.to_path_buf(),
            source,
        })
    }

    /// Read the lockfile under `root`, returning `None` when none exists.
    pub fn load_from_root(root: &Path) -> Result<Option<Lockfile>, ConfigError> {
        let path = Lockfile::path_in(root);
        if !path.is_file() {
            return Ok(None);
        }
        Lockfile::load(path).map(Some)
    }

    /// Write the lockfile under `root`.
    pub fn save_to_root(&self, root: &Path) -> Result<(), ConfigError> {
        let path = Lockfile::path_in(root);
        let text = toml::to_string_pretty(self).map_err(|err| {
            ConfigError::invalid(&path, format!("could not serialize lockfile: {err}"))
        })?;
        std::fs::write(&path, text).map_err(|source| ConfigError::Io { path, source })
    }
}
