#!/usr/bin/env bash
# Regenerate THIRD-PARTY-NOTICES.txt: the attribution that must ship with every
# distributed `peko` binary and with applications built by it.
#
# Two halves:
#   1. The Rust dependency graph, generated by `cargo about` from about.toml.
#   2. The bundled native components (BearSSL, webview, Android glue, LLVM),
#      hand-maintained in NOTICE-native.txt because cargo cannot see them.
#
# Run from anywhere; CI runs it to verify the checked-in file is current.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/THIRD-PARTY-NOTICES.txt"

if ! command -v cargo-about >/dev/null; then
  echo "cargo-about is not installed. Install it with:" >&2
  echo "  cargo install cargo-about --features cli" >&2
  exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

echo "generating the Rust dependency notices..."
(cd "$ROOT" && cargo about generate about.hbs -o "$tmp")

cat "$tmp" "$ROOT/NOTICE-native.txt" > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
